package com.project.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
public class SignupRequest {
    @NotBlank
    private String name;

    @Email
    private String email;

    private String mobileNumber;

    // Password is now generated by the backend, but we kept the field in case it's sent empty
    private String password;

    @NotBlank
    private String role; // ADMIN, DOCTOR, PATIENT

    // For Doctors only
    private String specialization;
    private String licenseNumber;
}
