package com.project.controller;

import com.project.dto.MessageResponse;
import com.project.entity.Doctor;
import com.project.entity.Role;
import com.project.entity.User;
import com.project.repository.AppointmentRepository;
import com.project.repository.ChatLogRepository;
import com.project.repository.DoctorRepository;
import com.project.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/users")
public class UserController {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private AppointmentRepository appointmentRepository;

    @Autowired
    private ChatLogRepository chatLogRepository;

    @Autowired
    private DoctorRepository doctorRepository;

    @GetMapping("/patients")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<List<User>> getPatients() {
        return ResponseEntity.ok(userRepository.findByRole(Role.PATIENT));
    }

    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<?> deleteUser(@PathVariable Long id) {
        User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("User not found"));

        // 1. Delete all chat logs generated by the user
        chatLogRepository.deleteAll(chatLogRepository.findByUserIdOrderByTimestampDesc(id));

        if (user.getRole() == Role.PATIENT) {
            // 2a. Delete patient's appointments
            appointmentRepository.deleteAll(appointmentRepository.findByPatientId(id));
        } else if (user.getRole() == Role.DOCTOR) {
            // 2b. Delete doctor's appointments and doctor profile
            Doctor doc = doctorRepository.findAll().stream()
                    .filter(d -> d.getUser().getId().equals(id))
                    .findFirst()
                    .orElse(null);

            if (doc != null) {
                appointmentRepository.deleteAll(appointmentRepository.findByDoctorId(doc.getId()));
                doctorRepository.delete(doc);
            }
        }

        // 3. Delete the base User account
        userRepository.delete(user);

        return ResponseEntity.ok(new MessageResponse("User deleted successfully"));
    }
}
